### ISSUE TITLE
Cannot query custom data after successful import 

### ISSUE THREAD

**Issue by woiza** [pelias/csv-importer#26]
I imported the following csv file (extract):

name,address,source,layer,lat,lon
AD,AD,custom,postalcode,42.5357,1.5571
AR,36,custom,postalcode,-25.0178,-59.6472
AR,41,custom,postalcode,-26.883,-65.1956
AR,44,custom,postalcode,-25.0513,-65.2488
AR,45,custom,postalcode,-23.5455,-64.0472
AR,46,custom,postalcode,-23.2252,-65.5236
BD,55,custom,postalcode,26.1669,89.1228
BD,53,custom,postalcode,26.0142,88.9168
BD,50,custom,postalcode,25.9689,88.6808

The idea is to have 2 digit postalcodes of all countries (I used geonames' csv file for this). How can I query the api to get the coordinates for a 2 digit postalcode in a country?

**Comment by orangejulius** [comment]
Hey @woiza,
Sorry about that, and thanks for reporting this. There's an extra configuration step required for custom data that wasn't well documented. I just opened https://github.com/pelias/api/pull/1297 and https://github.com/pelias/csv-importer/pull/37 to fix it. Can you take a look at those PRs and tell me if the explanations are clear?

Thanks!

**Comment by woiza** [comment]
Hi @orangejulius 
Should be fine now. I added the following to my pelias config:

"layers_by_source": {
        "geonames2d": [
          "country",
          "postalcode",
          "source",
          "layer"
        ],

Is there anything else I have to do?
