### ISSUE TITLE
import address not work

### ISSUE THREAD

**Issue by stefanocudini** [pelias/csv-importer#36]
hi I need to import a custom list of addresses from CSV files, I have coded the columns as indicated in the documentation
but after I execute import in ealstich search nothing is shown

this is a sample of my csv file
```csv
lon,lat,number,zipcode,street,layer,source
11.1258038738599,46.0384255604388,4,38123,,address,csv
11.1352742761045,46.0539734971077,101,38122,,address,csv
11.1251450165258,46.0535672621879,46,38123,Via Antonio Gramsci,address,csv
11.1363143019353,46.0627887491022,10,38122,,address,csv
11.126024700547,46.0564461996177,22,38122,,address,csv
11.1192645125392,46.0599223809797,1,38122,Via fratelli Perini,address,csv
11.1359105131297,46.0617807770361,9,38122,,address,csv
11.1467344763048,46.0752138268721,21,38121,,address,csv
11.1399449465559,46.0777789405135,13,38121,Via delle Marnighe,address,csv
```
this is my pelias.json file
```json
{
  "logger": {
    "level": "debug",
    "timestamp": false,
    "colorize": true
  },
  "esclient": {
    "apiVersion": "5.6",
    "hosts": [
      {
        "host": "elasticsearch"
      }
    ]
  },
  "elasticsearch": {
    "settings": {
      "index": {
        "refresh_interval": "10s",
        "number_of_replicas": "0",
        "number_of_shards": "1"
      }
    }
  },
  "acceptance-tests": {
    "endpoints": {
      "docker": "http://api:4000/v1/"
    }
  },
  "api": {
    "textAnalyzer": "libpostal",
    "services": {
      "placeholder": {
        "url": "http://placeholder:4100"
      },
      "pip": {
        "url": "http://pip:4200"
      },
      "interpolation": {
        "url": "http://interpolation:4300"
      },
      "libpostal": {
        "url": "http://libpostal:4400"
      }
    },
    "defaultParameters": {
      "focus.point.lat": 45.52,
      "focus.point.lon": -122.67
    }
  },
  "imports": {
    "adminLookup": {
      "enabled": false
    },
    "openstreetmap": {
      "leveldbpath": "/tmp",
      "datapath": "/data/openstreetmap",
      "import": [
        {
          "filename": "trentino-alto-adige.osm.pbf"
        }
      ]
    },
    "csv": {
      "datapath": "/data/csv",
      "files": [
        "trento_civici_strade.csv"
      ]
    },
    "whosonfirst": {
      "datapath": "/data/whosonfirst",
      "importVenues": false,
      "importPostalcodes": true,
      "importPlace": [
        "85685277"
      ]
    }
  }
}
```

**Comment by orangejulius** [comment]
Hey @stefanocudini,
Sorry about that, and thanks for reporting this. There's an extra configuration step required for custom data that wasn't well documented. I just opened https://github.com/pelias/api/pull/1297 and https://github.com/pelias/csv-importer/pull/37 to fix it. Can you take a look at those PRs and tell me if the explanations are clear?

Thanks!

**Comment by stefanocudini** [comment]
tnks @orangejulius how can I apply new config without reimport all data?
can i run only command *pelias compose up*??

**Comment by orangejulius** [comment]
Unfortunately `docker-compose` isn't smart enough to pick up changes to `pelias.json`, but 

```
pelias compose kill api
pelias compose up api
````

You shouldn't have to put anything in `layers_by_source` for the default data sources, those are already in the config and any additions will purely extend, not overwrite.

**Comment by stefanocudini** [comment]
yes but where I can put "layers_by_source"?? inside pelias.json?

i trying this configuration, but when i try ti request to APi it response empty result :( why?
```http://localhost:4000/v1/autocomplete?text=Via Antonio```
this address exists in my csv file in column address

```
"api": {
   ...
    "targets": {
      "layers_by_source": {
        "csv": ["address"]
      }
    }
  },
"imports": {
    ...
    "csv": {
      "datapath": "/data/csv",
      "files": [
        "trento_civici_strade.csv"
      ]
    },
}
```


this is my csv file
lon,lat,number,zipcode,street,**layer**,**source**
11.1258038738599,46.0384255604388,4,38123,,**address**,**csv**
11.1352742761045,46.0539734971077,101,38122,,address,csv
11.1251450165258,46.0535672621879,46,38123,**Via Antonio Gramsci**,address,csv
