### ISSUE TITLE
Add/update/remove custom addresses

### ISSUE THREAD

**Issue by umar18** [pelias/csv-importer#55]
Hello,
I have couple of questions:

1. Is **id** is important. I mean can i use same id for all addresses ? If i do what will happen ? 
2. How can i modify a single record which was previously imported ?
3. How can i remove a single record.
4. How can i remove all custom imported addresses ?
5. Is duplication handled ?

**Comment by missinglink** [comment]
Heya

1. https://github.com/pelias/csv-importer#id
2. You can reimport new data using the same ID, this will replace the old record
3. The CSV importer isn't able to handle deletions, see https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete.html
4. See https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html
5. Duplication is not handled at import time but the `pelias/api` code attempts to not show items in the response it things refer to the exact same thing. I would suggest you deduplicate your CSV file before importing it 😃
