### ISSUE TITLE
pelias import csv : no errors, files detected, but data not loaded

### ISSUE THREAD

**Issue by yossefaz** [pelias/csv-importer#75]
**Describe the bug**

After following step by step the data import process, with no visible bug / errors, my data is not loaded in the Elastic Search instance

**Steps to Reproduce**

1. go to this [repo](https://github.com/yossefaz/pelias-jerusalem ) and clone it (it contains all the required configuration based on the documentation)

2. Run the pelias build commands
3. Perform this request : http://localhost:4000/v1/search?text=האוניברסיטה
4. Even if the street name `האוניברסיטה` ("University" in hebrew) is present in the [data](https://github.com/yossefaz/pelias-jerusalem/blob/master/data/csv/adress.csv)  -see the `street` column - You should get an empty features array as I get : 

```

{
  "geocoding": {
    "version": "0.2",
    "attribution": "http://localhost:4000/attribution",
    "query": {
      "text": "האוניברסיטה",
      "size": 10,
      "layers": [
        "street",
        "country",
        "region",
        "county",
        "locality",
        "continent",
      ],
      "private": false,
      "focus.point.lat": 31.3,
      "focus.point.lon": 35.45,
      "lang": {
        "name": "English",
        "iso6391": "en",
        "iso6393": "eng",
        "via": "header",
        "defaulted": false
      },
      "querySize": 20,
      "parser": "pelias",
      "parsed_text": {
        "subject": "האוניברסיטה"
      }
    },
    "warnings": ["performance optimization: excluding 'address' layer"],
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1599579340661
  },
  "type": "FeatureCollection",
  "features": []
}

```

When I ran the command `curl localhost:9200/_cat/count` I got `1420`. Even If my csv contains more than 50K+ records. 

Here are some screenshot of  `pelias import csv`  command stdout : 

![Screenshot from 2020-09-08 18-49-02](https://user-images.githubusercontent.com/61141682/92498997-01127800-f204-11ea-9ad4-eec87d07af30.png)

![Screenshot from 2020-09-08 18-34-48](https://user-images.githubusercontent.com/61141682/92498394-3ec2d100-f203-11ea-943e-867787ad3c32.png)

As we can see here, the csv import has detected the csv files and even instantiate a stream reader for them..no error output.
But the records are not loaded.

In my repo I put a [sample](https://github.com/yossefaz/pelias-jerusalem/blob/master/data/csv/adress.csv) of the csv that I attempt to load.

There is also my configuration [`pelias.json`](https://github.com/yossefaz/pelias-jerusalem/blob/master/pelias.json) and my docker-compose there.

**Expected behavior**

As I followed step by step the required csv format and applied all the build / import command, I should be able to see the records appears after performing the request as shown ahead.

**Comment by missinglink** [comment]
The CSV data you linked shows the lat lon values as large decimal numbers when I would expect to see floats.

The coordinates should be in WGS84 , otherwise you'll need to reproject them before importing.

Another thing to check is that your ID are unique, especially between files, importing the same twice will update the existing record rather than creating a new one.

**Comment by missinglink** [comment]
Also you should set `api.targets.auto_discover` to true and restart the API server.

**Comment by yossefaz** [comment]
@missinglink thank you very much for your suggestion. Indeed `lat` and `lon` are currently in EPSG:2039 (I did not see in the doc that it must be in WGS84) so I will convert them and will try again. 

For the `api.targets.autodiscover` parameter, I tried `true` but did not help (at least with this data...I'll convert the data and try again with that param set to `true` and let you know).

Many thanks for your time 🙏

**Comment by missinglink** [comment]
A count of `1420` from `/_cat/count` is indicative that something is going wrong with the import, you should fix that first.
I strongly suspect that the IDs are not unique, but you said that's not the case, then maybe it's due to the coordinates...

Once you've got that working you'll benefit from `api.targets.auto_discover: true` because otherwise your user-defined layer/source `custom/jerumuni` will not be known to the API server.

**Comment by yossefaz** [comment]
@missinglink : Thank you again for all your advice.
Here is what I achieved so far : 

- [x] I tranform all the lat lon from EPSG:2039 to WGS84 (you can see [here](https://github.com/yossefaz/pelias-jerusalem/blob/master/data/csv/adress.csv))

- [x] imported data again : Now , if I perform a `_cat/count` I got 1432 (1420 + 12 records (from the csv) which means that my records has been commited into the elastic search instance : Great.

- [x] set `api.targets.auto_discover: true`

But I still do not receive any features in the features collection response, even if the data is present in one or more rows : 

http://localhost:4000/v1/search?text=האוניברסיטה

So the good thing in that the data is indeed loaded by the importer to elasticsearch, but the API still does not query it....even if I defined the target source in the api wiht the layer name and source that are in my csv.

**Comment by yossefaz** [comment]
I've found the issue !!
I've changed the `street` column to `name` and it worked. From the [documentation](https://github.com/pelias/csv-importer/#name) it is not clear that this field is mandatory. So I wonder : does the query is performed only on this field `name` ? Does the `street` field is only here to be returned but is not queried ?

**Comment by missinglink** [comment]
Agh ok, good catch.

Generally speaking everything has to have name, addresses can have a `street` property but its purpose is to provide more granular separation of the individual parts of the address.

For streets we usually duplicate the street name, so it appears once in the name field and once in the street field.

**Comment by orangejulius** [comment]
Hi @yossefaz looks like you've figured everything out here, and thanks much for the feedback on the README. If there's anything else let us know!
