### ISSUE TITLE
Import into Pelias German house numbers with CSV importer

### ISSUE THREAD

**Issue by dawidl11** [pelias/csv-importer#98]
Hi there,

**What I am doing:**
in my project I want to import a CSV file with German addresses into Pelias. Using the defaults, I mapped my address data to the Pelias import CSV accordingly. 

**Problem:**
However, I encountered a problem in the process:
German house numbers consist of a number and often an additional house number suffix, e.g. "11b" or "7a". Pelias expects the attribute "housenumber" to be a number and not a string, otherwise it returns an error message during import. 

**Question:**
Is there any way to import my house number with the house number suffix into Pelias using the CSV importer?

Many thanks in advance for the answers!
Dawid

**Comment by missinglink** [comment]
That's odd, are you sure? I looked at the code and didn't see anywhere which might assert that a housenumber must be entirely numeric.

Can you please provide additional information about the error.

**Comment by dawidl11** [comment]
Hi, that's right, actually the house numbers were not the problem. The problem was in another place (probably the coordinates)....
Thanks for the quick reply and sorry for the misinformation.
